import codecs

replacements = {
    ' giây nữa để huỷ số': ' seconds to release number',
    ' luồng chờ. Tổng số lượng mới: ': ' pending threads. New total: ',
    ' lần.': ' times.',
    ' trên Firefox (trạng thái: ': ' on Firefox (status: ',
    ' trên hệ thống Firefox. Lý do: ': ' on Firefox system. Reason: ',
    ' vào file.': ' to file.',
    ' vì các máy đã bắt đầu chạy. Tổng số mới: ': ' because devices have started. New total: ',
    ' đ': ' VND',
    '. Lý do: ': '. Reason: ',
    'Bỏ qua': 'Skip',
    'Chào mừng': 'Welcome',
    'Chưa nhận được SMS, vui lòng gọi API huỷ số (Release number) trước': 'SMS not received, please call Release number API first',
    'Chỉ giảm được ': 'Can only reduce ',
    'Chọn': 'Select',
    'Cập nhật ảnh': 'Update avatar',
    'Dịch vụ (Service ID) không tồn tại': 'Service ID does not exist',
    'Dịch vụ chưa được kiểm duyệt': 'Service not approved yet',
    'Dịch vụ này không cho phép chỉ định số điện thoại': 'Service does not allow specifying phone number',
    'Dịch vụ này không cho phép gửi SMS': 'Service does not allow sending SMS',
    'Dịch vụ đã bị vô hiệu hóa': 'Service disabled',
    'Giới tính': 'Gender',
    'Huỷ quá nhiều lần, tài khoản đã tự động bị khóa (Blacklist)': 'Canceled too many times, account auto blacklisted',
    'Không có số': 'No number',
    'Không có số nào phù hợp với điều kiện đã chọn': 'No matching number found',
    'Không có từ khóa, vui lòng liên hệ CSKH': 'No keyword, contact support',
    'Không gửi yêu cầu lặp đi lặp lại nhiều lần': 'Do not send repeated requests',
    'Lý do (reason) không được để trống': 'Reason cannot be empty',
    'Lưu thành công': 'Saved successfully',
    'LỖI MẠNG: ': 'NETWORK ERROR: ',
    'Lỗi Token: ': 'Token Error: ',
    'Lỗi hệ thống hoặc bị chặn': 'System error or blocked',
    'Lỗi không xác định': 'Unknown error',
    'Lỗi mạng': 'Network error',
    'Lỗi tham số / Đang chờ': 'Parameter error / Waiting',
    'Lỗi tạo tài khoản': 'Account creation error',
    'Lỗi: ': 'Error: ',
    'Mật khẩu không được để trống': 'Password cannot be empty',
    'Ngẫu nhiên': 'Random',
    'Nhập số điện thoại': 'Enter phone number',
    'Nhập tên': 'Enter name',
    'Nội dung tin nhắn không đúng quy tắc': 'Invalid SMS content rule',
    'Nội dung tin nhắn không được để trống': 'SMS content cannot be empty',
    'Nữ': 'Female',
    'Pkey (Mã số) không hợp lệ': 'Invalid Pkey',
    'Pkey/Token không hợp lệ': 'Invalid Pkey/Token',
    'Quá nhiều số': 'Too many numbers',
    'Quá nhiều số đang giữ chưa huỷ, vui lòng nạp thêm tiền hoặc chủ động huỷ số cũ': 'Too many numbers held, please top up or release old ones',
    'Quốc gia bị lỗi/không hợp lệ': 'Invalid country',
    'SMS đang được gửi đi, không được phép huỷ': 'SMS is sending, cannot release',
    'Sinh nhật': 'Birthday',
    'Săn Quà Ngay': 'Hunt Gifts Now',
    'Số dư không': 'Insufficient balance',
    'Số dư không đủ, vui lòng nạp thêm tiền': 'Insufficient balance, please top up',
    'Số dư: --': 'Balance: --',
    'Số lượng (Firefox Auto):': 'Amount (Firefox Auto):',
    'Số lượng Firefox Auto phải là số nguyên hợp lệ.': 'Amount must be a valid integer.',
    'Số lượng Firefox Auto phải lớn hơn 0.': 'Amount must be greater than 0.',
    'Số lượng không thay đổi.': 'Amount unchanged.',
    'Số lượng phải > 0': 'Amount must be > 0',
    'Số người nhận không được để trống': 'Recipient number cannot be empty',
    'Số điện thoại': 'Phone number',
    'Số điện thoại không khả dụng': 'Phone number unavailable',
    'Số điện thoại không khả dụng, vui lòng bỏ qua': 'Phone number unavailable, please skip',
    'Số điện thoại không khả dụng, vui lòng bỏ qua số này': 'Phone number unavailable, please skip this one',
    'Số điện thoại đã bị đưa vào danh sách đen, vui lòng bỏ qua': 'Phone number blacklisted, please skip',
    'Tiếp tục': 'Continue',
    'Token không': 'Invalid token',
    'Token không hợp lệ, vui lòng đăng nhập lại': 'Invalid token, please re-login',
    'Token không tồn tại': 'Token does not exist',
    'Token đã bị vô hiệu hóa': 'Token disabled',
    'Tài khoản (ApiName) đã bị vô hiệu hóa': 'Account disabled',
    'Tài khoản của bạn không được cấp quyền sử dụng chức năng Black number': 'No permission for Black number',
    'Tên của bạn': 'Your name',
    'Tên đăng nhập (ApiName) không được để trống': 'Username cannot be empty',
    'Tên đăng nhập hoặc mật khẩu không đúng': 'Invalid username or password',
    'Tên đăng nhập không được chứa ký tự tiếng Trung': 'Username cannot contain Chinese',
    "Tên đăng nhập không được chứa ký tự đặc biệt '|'": "Username cannot contain '|'",
    'Tìm bạn': 'Find friends',
    'Tìm bạn bè': 'Find friends',
    'Tìm kiếm': 'Search',
    'Tính năng này dùng để thêm/bớt số lượng khi tool ĐANG CHẠY. Hiện tại tool đang dừng, bạn chỉ cần sửa số và ấn Start.': 'This feature is for modifying amount while running. Tool is stopped, just edit amount and press Start.',
    'Vui lòng nhập Firefox Token trước.': 'Please enter Firefox Token first.',
    'Vui lòng nhập số nguyên hợp lệ.': 'Please enter a valid integer.',
    'Vui lòng đợi ': 'Please wait ',
    'Vui lòng đợi 60 giây trước khi yêu cầu lại': 'Please wait 60s before retrying',
    'Ví dụ: 10': 'Example: 10',
    'Xem kết quả': 'View results',
    'Xác nhận': 'Confirm',
    'Yêu cầu quá nhanh từ cùng 1 IP, thử lại sau 1 phút': 'Request too fast, try again in 1 minute',
    '] ADB chưa ngắt sau reset, quay lại Xtoolz bấm lại...': '] ADB not disconnected after reset, back to Xtoolz to tap again...',
    '] ADB đã ngắt trong lúc mở Xtoolz, coi như reset đã ăn. Chuyển sang chờ reconnect...': '] ADB disconnected while opening Xtoolz, reset accepted. Waiting to reconnect...',
    '] Bị khóa sau khi giải Captcha. Page=': '] Blocked after Captcha. Page=',
    '] Bỏ cuộc, không thuê được số sau 3 lần thử.': '] Gave up, failed to rent number after 3 tries.',
    '] Chưa rõ màn hình sau captcha, page=': '] Unknown screen after captcha, page=',
    '] Chờ biên lai gửi SMS...': '] Waiting for SMS receipt...',
    '] Gửi SMS Firefox lỗi: ': '] Firefox SMS error: ',
    '] Gửi SMS Firefox tới ': '] Send Firefox SMS to ',
    '] Không mở được Xtoolz package=': '] Failed to open Xtoolz package=',
    '] Không nhận được biên lai gửi SMS.': '] Did not receive SMS receipt.',
    '] Không phải màn OTP, chưa gửi SMS. Page=': '] Not OTP screen, SMS not sent. Page=',
    '] Không thể lấy lại pkey mới cho số ': '] Cannot get new pkey for ',
    '] Không tìm thấy màn hình chọn Giới tính': '] Gender screen not found',
    '] Không ở captcha, quét lại màn hình trước khi fail. page=': '] Not in captcha, rescanning before fail. page=',
    '] Lỗi ghi file sdt: ': '] Phone file write error: ',
    '] Lỗi khi chờ biên lai SMS Firefox: ': '] Error waiting for SMS receipt: ',
    '] Lỗi thuê số (lần ': '] Rent number error (try ',
    '] Timeout chờ biên lai SMS Firefox.': '] Timeout waiting for SMS receipt.',
    '] Timeout/Lỗi màn sau captcha: ': '] Timeout/Error after captcha: ',
    '] Vẫn ở captcha, chờ thêm trước khi retry.': '] Still in captcha, waiting before retry.',
    '] Vẫn ở captcha, thử lại.': '] Still in captcha, retrying.',
    '] Zalo đang xử lý sau captcha, tiếp tục chờ...': '] Zalo processing after captcha, waiting...',
    '] Zalo đang xử lý sau captcha, tiếp tục chờ... texts=': '] Zalo processing after captcha, waiting... texts=',
    '] Đang chờ kết nối 4G ổn định...': '] Waiting for stable 4G connection...',
    '] Đang xin cấp lại pkey mới cho số ': '] Requesting new pkey for ',
    '] Đã Blacklist số ': '] Blacklisted number ',
    '] Đã có kết nối mạng (4G)!': '] Network connected (4G)!',
    '] Đã feedback SUCCESS lên Firefox cho số ': '] Feedback SUCCESS to Firefox for ',
    '] Đã lấy pkey mới thành công. Bắt đầu chờ mã OTP Zalo...': '] Got new pkey. Waiting for Zalo OTP...',
    '] Đã lấy số thành công: ': '] Number rented successfully: ',
    '] Đã nhận được biên lai gửi SMS thành công từ Firefox.': '] SMS receipt received successfully from Firefox.',
    '] Đã nén ảnh Captcha siêu nhẹ để tăng tốc độ upload.': '] Compressed Captcha image to speed up upload.',
    '] Đã release/setRel số ': '] Released number ',
    '] Đã thấy màn OTP trong lúc trạng thái còn captcha, nhảy sang bước OTP.': '] Found OTP screen while in captcha state, jumping to OTP.',
    '] ⚠️ PHÁT HIỆN THIẾT BỊ TREO/LAG (UI Dump thất bại 4 lần liên tiếp). Ép dừng tiến trình để tránh kẹt số!': '] ⚠️ DEVICE LAG DETECTED (UI Dump failed 4 times). Stopping thread to avoid stuck numbers!',
    '] ❌ Lỗi tạo tài khoản (Account creation failed).': '] ❌ Account creation failed.',
    '] ❌ Phát hiện lỗi: Tài khoản đã tồn tại hoặc Bị khóa. Ghi số ': '] ❌ Error detected: Account exists or Blocked. Logging number ',
    '] ❌ Thất bại Captcha sau ': '] ❌ Captcha failed after ',
    '] ❌ Thất bại nhận OTP từ Firefox - Bỏ qua.': '] ❌ Failed to get OTP from Firefox - Skipping.',
    'bị cấm': 'banned',
    'bị khóa': 'locked',
    'chính sách quyền riêng tư': 'privacy policy',
    'chúc mừng': 'congratulations',
    'cá nhân': 'profile',
    'giới tính': 'gender',
    'gửi tin nhắn': 'send message',
    'không hợp lệ': 'invalid',
    'không thành công': 'unsuccessful',
    'mã xác thực': 'verification code',
    'mảnh ghép': 'puzzle',
    'nhập mã': 'enter code',
    'nhập tên': 'enter name',
    'quan tâm': 'interested',
    'quà': 'gift',
    'quét mã': 'scan qr',
    'sinh nhật': 'birthday',
    'soạn': 'compose',
    'săn quà ngay': 'hunt gifts now',
    'theo dõi oa': 'follow oa',
    'thành công': 'success',
    'thể lệ tham dự': 'rules of participation',
    'trang chủ': 'home',
    'trượt': 'slide',
    'tài khoản bị khóa': 'account locked',
    'tài khoản đã tồn tại': 'account exists',
    'tên của bạn': 'your name',
    'tôi đã đọc': 'i have read',
    'tôi đồng ý': 'i agree',
    'tạm khóa': 'temporarily locked',
    'vô hiệu hóa': 'disabled',
    'xác minh': 'verify',
    'xác nhận': 'confirm',
    'Đang chờ mã xác minh (chưa có SMS)': 'Waiting for verification code (no SMS yet)',
    'Đang kiểm tra...': 'Checking...',
    'Điều khoản': 'Terms',
    'Đã giảm ': 'Reduced ',
    'Đã nhận được SMS, không thể huỷ số': 'SMS received, cannot release number',
    'Đã thêm ': 'Added ',
    'Đăng ký': 'Sign up',
    'Để bắt đầu': 'To get started',
    'Để cung cấp': 'To provide',
    'Để sau': 'Later',
    'Đồng ý': 'Agree',
    'Đổi': 'Change',
    'Đổi tên': 'Change name',
    'Độ dài mật khẩu phải từ 3-30 ký tự': 'Password length must be 3-30 characters',
    'Độ dài tên đăng nhập phải từ 3-30 ký tự': 'Username length must be 3-30 characters',
    'đang xử lý': 'processing',
    'điều khoản': 'terms',
    'đã tham gia': 'joined',
    'đóng': 'close',
    'để cung cấp': 'to provide',
    '❌ Lỗi thuê số': '❌ Rent error',
    '🔄 Đợi 4G...': '🔄 Waiting for 4G...',
    '🔍 Kiểm tra Số dư': '🔍 Check Balance'
}

with codecs.open('c:/Users/congn/Pictures/tool/server/toiuu.py', 'r', 'utf-8') as f:
    content = f.read()

for k, v in replacements.items():
    content = content.replace('\"' + k + '\"', '\"' + v + '\"')
    content = content.replace('\'' + k + '\'', '\'' + v + '\'')

with codecs.open('c:/Users/congn/Pictures/tool/server/toiuu.py', 'w', 'utf-8') as f:
    f.write(content)
